/*
 * mover/components.rs — typestate + bundle for the Tnua A/B path.
 *
 * `Oni2Scheme` is the minimum viable `TnuaScheme` for Phase 1: the walk basis
 * is the only thing that runs every frame; `Jump` is declared as a placeholder
 * action to satisfy the `#[derive(TnuaScheme)]` macro (which doesn't accept
 * empty enums) but is never fed by the bridge — jump fidelity is Phase 2 work.
 *
 * `Oni2SchemeConfig` is the asset Tnua reads each tick. Defaults are tuned
 * loosely to the moverdata.h values surfaced during the mover.cpp dig:
 *   - max_slope ≈ 20° → slide_steepness (walkable threshold)
 *   - float_height ≈ 0.3 m → MaxStepUpDistance (Tnua absorbs this much
 *     vertical play continuously, so stairs/curbs are handled by the spring,
 *     not by an explicit step-up probe).
 *
 * The intermediate "slide but don't walk" slope band (between slide_steepness
 * and wall_steepness in mover.cpp) has no direct Tnua knob — implementing it
 * needs a custom basis modifier. Deferred.
 */
use avian3d::prelude::*;
use bevy::prelude::*;
use bevy_tnua::TnuaScheme;
use bevy_tnua::builtins::{
    TnuaBuiltinJump, TnuaBuiltinJumpConfig, TnuaBuiltinWalk, TnuaBuiltinWalkConfig,
};
use bevy_tnua::control_helpers::{TnuaAirActionDefinition, TnuaHasTargetEntity};
use bevy_tnua::prelude::*;
use bevy_tnua_avian3d::prelude::*;

/// Per-entity Tnua control scheme. Walk is the basis; Jump is declared but
/// never activated in Phase 1.
#[derive(TnuaScheme)]
#[scheme(basis = TnuaBuiltinWalk)]
pub enum Oni2Scheme {
    Jump(TnuaBuiltinJump),
}

impl TnuaAirActionDefinition for Oni2Scheme {
    fn is_air_action(action: Self::ActionDiscriminant) -> bool {
        matches!(action, Oni2SchemeActionDiscriminant::Jump)
    }
}

impl TnuaHasTargetEntity for Oni2Scheme {
    fn target_entity(_: &Self::ActionState) -> Option<Entity> {
        None
    }
}

// `Oni2SchemeConfig` is auto-generated by `#[derive(TnuaScheme)]` above —
// the macro produces a struct with one field per variant (lowercased name)
// plus a `basis` field of the basis-builtin's Config type. Loose port of
// moverdata.h Phase 1 fields:
//   - float_height ≈ MaxStepUpDistance (~0.3m). Tnua's spring absorbs this
//     much vertical play, replacing the legacy step-up probe.
//   - max_slope ≈ slide_steepness (walkable cutoff, ~20°).
//
// Numbers are starting points — tune by feel during A/B.
impl Default for Oni2SchemeConfig {
    fn default() -> Self {
        Self {
            basis: TnuaBuiltinWalkConfig {
                float_height: 1.0,
                max_slope: std::f32::consts::FRAC_PI_8,
                ..Default::default()
            },
            jump: TnuaBuiltinJumpConfig {
                height: 1.5,
                ..Default::default()
            },
        }
    }
}

/// Phase-1 runtime state for the Tnua-backed mover. Reserved for Mover Gem
/// (backward-motion rejection) and wall-slam detection — neither populated
/// yet, so the field is currently unread.
#[derive(Component, Default)]
pub struct MoverState {
    #[allow(dead_code)]
    pub last_grounded: bool,
}

/// Tnua-flavored sibling of `combat::CreaturePhysicsBundle`. Same capsule
/// dimensions, but Dynamic body (Tnua requires Dynamic) plus the Tnua control
/// components.
///
/// Spawn sites pick this vs the legacy bundle based on `MoverBackend`.
#[derive(Bundle)]
pub struct TnuaCreaturePhysicsBundle {
    pub rigid_body: RigidBody,
    pub collider: Collider,
    pub locked_axes: LockedAxes,
    pub linear_velocity: LinearVelocity,
    pub gravity_scale: GravityScale,
    pub controller: TnuaController<Oni2Scheme>,
    pub config: TnuaConfig<Oni2Scheme>,
    pub sensor_shape: TnuaAvian3dSensorShape,
    pub state: MoverState,
    /// Characters never sleep — see the note on
    /// `combat::CreaturePhysicsBundle::sleeping_disabled`.
    pub sleeping_disabled: SleepingDisabled,
    /// Characters don't physically collide with each other — see
    /// `combat::bundles::character_collision_layers`.
    pub collision_layers: CollisionLayers,
}

impl TnuaCreaturePhysicsBundle {
    /// Build a Dynamic capsule + Tnua controller. `config_handle` is shared
    /// across all creatures using the same scheme (typically one global
    /// handle stored as a resource at startup).
    pub fn new(
        capsule_radius: f32,
        capsule_length: f32,
        config_handle: Handle<Oni2SchemeConfig>,
    ) -> Self {
        Self {
            rigid_body: RigidBody::Dynamic,
            collider: Collider::capsule(capsule_radius, capsule_length),
            locked_axes: LockedAxes::new()
                .lock_rotation_x()
                .lock_rotation_y()
                .lock_rotation_z(),
            linear_velocity: LinearVelocity::default(),
            gravity_scale: GravityScale(1.0),
            controller: TnuaController::<Oni2Scheme>::default(),
            config: TnuaConfig::<Oni2Scheme>(config_handle),
            // Ground sensor must be a sphere (or low-profile shape). A
            // tall capsule's own length pushes the detected-ground point
            // upward and the float spring settles the body ~0.5m too high.
            sensor_shape: TnuaAvian3dSensorShape(Collider::sphere(capsule_radius * 0.95)),
            state: MoverState::default(),
            sleeping_disabled: SleepingDisabled,
            collision_layers: crate::combat::bundles::character_collision_layers(),
        }
    }
}
