/// Token codes matching the C++ ScrOni tokenizer.
/// Keywords are case-insensitive; identifiers preserve case.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum TokenCode {
    // Literals & identifiers
    Error,
    Eof,
    IntegerConstant,
    FloatConstant,
    StringConstant,
    Identifier,

    // Operators
    Plus,
    Percent,
    Minus,
    Star,
    Slash,
    LeftParen,
    RightParen,
    LeftCurlyBracket,
    RightCurlyBracket,
    Equal,
    NotEqual,
    Comma,
    Period,
    Colon,
    Greater,
    GreaterOrEqual,
    Less,
    LessOrEqual,
    Cross,

    // Keywords (alphabetical, matching C++ TOKENLIST)
    ActorEnabled,
    Accuracy,
    Active,
    ActorList,
    Add,
    AimingAtMe,
    Alive,
    All,
    Ally,
    AmbientSound,
    AmbientSoundStatus,
    And,
    Angle,
    Armed,
    As,
    Asleep,
    Assign,
    Attack,
    Attacking,
    At,
    Background,
    Backward,
    Begin,
    Blocking,
    BlockingCommandFailed,
    Bone,
    Bullets,
    CameraGetPosition,
    CameraReset,
    CameraMode,
    CameraLetterbox,
    CameraFollowActor,
    CameraMoveToActor,
    CameraMoveToPoint,
    CameraMoveToRailPoint,
    CameraMoveAlongRail,
    CameraCutToActor,
    CameraCutToPoint,
    CameraSetFOV,
    CameraSetPackage,
    CameraShake,
    CameraTrackActor,
    CameraTrackPoint,
    Child,
    ChildDone,
    ChildHome,
    ChildStack,
    ChildStop,
    ChildSwitch,
    Clamber,
    Clear,
    Color,
    Component,
    Cone,
    ControlAnimation,
    ControlHead,
    Cos,
    CreateGroup,
    CreateSection,
    Creature,
    Crouched,
    CutScenesEnabled,
    Damage,
    DampenTime,
    Defend,
    DeltaHeight,
    Destroy,
    DestroyGroup,
    DestroySection,
    Direction,
    Disable,
    Distance,
    Do,
    Done,
    Dormant,
    DrawText,
    DrawWeapon,
    Drop,
    Dropoff,
    Else,
    End,
    EndCutSceneAudio,
    EndGrapple,
    Enemy,
    Exists,
    Exit,
    Face,
    Facing,
    FadeIn,
    FadeOut,
    Fight,
    Fighting,
    FightAndShoot,
    Find,
    FireActor,
    FirePos,
    FiringAtMe,
    First,
    Float,
    Follow,
    For,
    Forever,
    Form,
    Forward,
    Frequency,
    From,
    Game,
    GetActiveWeapon,
    GetActorsInGroup,
    GetCheckPointIndex,
    GetCrouch,
    GetCurvePhase,
    GetCurveReachedEnd,
    GetCurveReachedGoto,
    GetCurveReachedStart,
    GetDetectedActor,
    GetFaction,
    GetFollowers,
    GetGroup,
    GetLastHitType,
    GetNumActorsInGroup,
    GetNumKnockdowns,
    GetNumWeapons,
    GetHud,
    GetScript,
    GetUIItemValue,
    GetUnbreakable,
    GetWeaponAmmo,
    GetWeaponType,
    Goto,
    GotoCurveKnot,
    GotoCurveLerp,
    GotoCurvePhase,
    Grappled,
    Grappling,
    GrapplingMe,
    Group,
    GroupExists,
    Guid,
    Hang,
    Hanging,
    HasHitch,
    Health,
    Heard,
    Hit,
    Hold,
    HolsterWeapon,
    Home,
    Idle,
    If,
    In,
    IncomingAttack,
    IncomingAttackTime,
    IncomingAttackWillBlock,
    Index,
    Integer,
    Intensity,
    Is,
    IsDone,
    IsHome,
    IsRestricted,
    JoinGroup,
    Jump,
    KnockedDown,
    Ks,
    Label,
    Leader,
    LeaveGroup,
    Left,
    Level,
    LevelComplete,
    LineOfSight,
    Listen,
    Location,
    Log,
    Look,
    Loop,
    Magnitude,
    MakeExplosion,
    MakeFX,
    MakeNoise,
    MakeProjectile,
    MakeString,
    Max,
    Me,
    Miss,
    Min,
    MusicPlay,
    MusicStop,
    Name,
    NavPoint,
    Neutral,
    Next,
    Normalize,
    Not,
    Of,
    Offset,
    OnCamera,
    OnlyRunning,
    OnlyStanding,
    Or,
    Orientation,
    PadRumbleLargeMotor,
    PadRumbleLargeMotorStop,
    PadRumblePause,
    PadRumbleResume,
    PadRumbleSmallMotor,
    PadRumbleSmallMotorStop,
    PadRumbleStopMotors,
    Parent,
    Pass,
    Path,
    Patrol,
    Pause,
    Pickup,
    Pitch,
    PitchRamp,
    Play,
    PlayAmbientSound,
    PlayActionAnimation,
    PlayAnimation,
    Player,
    PlayerTaskBegin,
    PlayerTaskSuccessful,
    PlayerTaskFailure,
    Position,
    RampUpTime,
    Random,
    RandomRange,
    RandomRangeFloat,
    Range,
    Rate,
    ReceiveAction,
    ReceiveMessage,
    Remove,
    ResetHealth,
    Restart,
    Retreat,
    Right,
    Room,
    RunGame,
    SavePoint,
    Scan,
    Script,
    Seconds,
    SectionCreated,
    SendAction,
    SendGroupMessage,
    SendGroupMembersMessage,
    SendMessage,
    Sequence,
    Set,
    SetActiveWeapon,
    SetActorEnabled,
    SetAttackTable,
    SetCrouch,
    SetCurve,
    SetCurveKnot,
    SetCurveKs,
    SetCurveLerp,
    SetCurveLookAlongDistance,
    SetCurveLookAlongDirection,
    SetCurveLookAtActor,
    SetCurvePhase,
    SetCurvePingPong,
    SetCurveSpeed,
    SetEndFrame,
    SetFaction,
    SetFogClamp,
    SetFogColor,
    SetFogPalettePower,
    SetFogRange,
    SetFogType,
    SetFullScreenColor,
    SetFullScreenMotionBlur,
    SetFrame,
    SetHealth,
    SetHud,
    SetLerpCurve,
    SetLookUpCurve,
    SetLightParameter,
    SetRate,
    SetShaderGlobal,
    SetShaderLocal,
    SetStartFrame,
    SetUnbreakable,
    SetUpdateState,
    SetWeaponChargeState,
    SetWeaponFireMode,
    Shoot,
    ShootDistance,
    Sin,
    Size,
    Sort,
    Sound,
    Spawn,
    Sqrt,
    Speed,
    SpotAngle,
    Stack,
    StackDump,
    Start,
    StartCutSceneAudio,
    StartFighting,
    StartShooting,
    Status,
    Stop,
    StringKw, // "string" keyword (renamed to avoid Rust conflict)
    SuccessiveAttacks,
    Support,
    Switch,
    TakeCover,
    Teleport,
    Then,
    Time,
    Timer,
    Times,
    To,
    TotalTime,
    TrackActor,
    TrackClosest,
    TrackPos,
    TriggerInside,
    TriggerOutside,
    TriggerEntered,
    TriggerExited,
    TriggerGetActorsInside,
    Turret,
    Unarmed,
    UsePad,
    Uses,
    Variable,
    Vector,
    Volume,
    VolumeRamp,
    WeaponDrawn,
    Whenever,
    While,
    With,
    Within,
    X,
    Y,
    Z,
}

/// A single token with source location and payload.
#[derive(Debug, Clone)]
pub struct Token {
    pub code: TokenCode,
    pub line: usize,
    pub col: usize,
    pub text: String,
    pub int_value: i32,
    pub float_value: f32,
}

impl Token {
    pub fn new(code: TokenCode, line: usize, col: usize, text: String) -> Self {
        Self { code, line, col, text, int_value: 0, float_value: 0.0 }
    }

    pub fn eof(line: usize, col: usize) -> Self {
        Self::new(TokenCode::Eof, line, col, String::new())
    }
}

/// Build keyword lookup table. Case-insensitive: all keys are lowercase.
pub fn keyword_table() -> std::collections::HashMap<String, TokenCode> {
    use TokenCode::*;
    let pairs: &[(&str, TokenCode)] = &[
        ("actorenabled", ActorEnabled),
        ("accuracy", Accuracy),
        ("active", Active),
        ("actorlist", ActorList),
        ("add", Add),
        ("aimingatme", AimingAtMe),
        ("alive", Alive),
        ("all", All),
        ("ally", Ally),
        ("ambientsound", AmbientSound),
        ("ambientsoundstatus", AmbientSoundStatus),
        ("and", And),
        ("angle", Angle),
        ("armed", Armed),
        ("as", As),
        ("asleep", Asleep),
        ("assign", Assign),
        ("attack", Attack),
        ("attacking", Attacking),
        ("at", At),
        ("background", Background),
        ("backward", Backward),
        ("begin", Begin),
        ("blocking", Blocking),
        ("blockingcommandfailed", BlockingCommandFailed),
        ("bone", Bone),
        ("bullets", Bullets),
        ("cameragetposition", CameraGetPosition),
        ("camerareset", CameraReset),
        ("cameramode", CameraMode),
        ("cameraletterbox", CameraLetterbox),
        ("camerafollowactor", CameraFollowActor),
        ("cameramovetoactor", CameraMoveToActor),
        ("cameramovetopoint", CameraMoveToPoint),
        ("cameramovetoRailpoint", CameraMoveToRailPoint),
        ("cameramovealongrail", CameraMoveAlongRail),
        ("cameracuttoactor", CameraCutToActor),
        ("cameracuttopoint", CameraCutToPoint),
        ("camerasetfov", CameraSetFOV),
        ("camerasetpackage", CameraSetPackage),
        ("camerashake", CameraShake),
        ("cameratrackactor", CameraTrackActor),
        ("cameratrackpoint", CameraTrackPoint),
        ("child", Child),
        ("childdone", ChildDone),
        ("childhome", ChildHome),
        ("childstack", ChildStack),
        ("childstop", ChildStop),
        ("childswitch", ChildSwitch),
        ("clamber", Clamber),
        ("clear", Clear),
        ("color", Color),
        ("component", Component),
        ("cone", Cone),
        ("controlanimation", ControlAnimation),
        ("controlhead", ControlHead),
        ("cos", Cos),
        ("creategroup", CreateGroup),
        ("createsection", CreateSection),
        ("creature", Creature),
        ("crouched", Crouched),
        ("cutscenesenabled", CutScenesEnabled),
        ("damage", Damage),
        ("dampentime", DampenTime),
        ("defend", Defend),
        ("deltaheight", DeltaHeight),
        ("destroy", Destroy),
        ("destroygroup", DestroyGroup),
        ("destroysection", DestroySection),
        ("direction", Direction),
        ("disable", Disable),
        ("distance", Distance),
        ("do", Do),
        ("done", Done),
        ("dormant", Dormant),
        ("drawtext", DrawText),
        ("drawweapon", DrawWeapon),
        ("drop", Drop),
        ("dropoff", Dropoff),
        ("else", Else),
        ("end", End),
        ("endcutsceneaudio", EndCutSceneAudio),
        ("endgrapple", EndGrapple),
        ("enemy", Enemy),
        ("exists", Exists),
        ("exit", Exit),
        ("face", Face),
        ("facing", Facing),
        ("fadein", FadeIn),
        ("fadeout", FadeOut),
        ("fight", Fight),
        ("fighting", Fighting),
        ("fightandshoot", FightAndShoot),
        ("find", Find),
        ("fireactor", FireActor),
        ("firepos", FirePos),
        ("firingatme", FiringAtMe),
        ("first", First),
        ("float", Float),
        ("follow", Follow),
        ("for", For),
        ("forever", Forever),
        ("form", Form),
        ("forward", Forward),
        ("frequency", Frequency),
        ("from", From),
        ("game", Game),
        ("getactiveweapon", GetActiveWeapon),
        ("getactorsingroup", GetActorsInGroup),
        ("getcheckpointindex", GetCheckPointIndex),
        ("getcrouch", GetCrouch),
        ("getcurvephase", GetCurvePhase),
        ("getcurvereachedend", GetCurveReachedEnd),
        ("getcurvereachedgoto", GetCurveReachedGoto),
        ("getcurvereachedstart", GetCurveReachedStart),
        ("getdetectedactor", GetDetectedActor),
        ("getfaction", GetFaction),
        ("getfollowers", GetFollowers),
        ("getgroup", GetGroup),
        ("getlasthittype", GetLastHitType),
        ("getnumactorsingroup", GetNumActorsInGroup),
        ("getnumknockdowns", GetNumKnockdowns),
        ("getnumweapons", GetNumWeapons),
        ("gethud", GetHud),
        ("getscript", GetScript),
        ("getuiitemvalue", GetUIItemValue),
        ("getunbreakable", GetUnbreakable),
        ("getweaponammo", GetWeaponAmmo),
        ("getweapontype", GetWeaponType),
        ("goto", Goto),
        ("gotocurveknot", GotoCurveKnot),
        ("gotocurvelerp", GotoCurveLerp),
        ("gotocurvephase", GotoCurvePhase),
        ("grappled", Grappled),
        ("grappling", Grappling),
        ("grapplingme", GrapplingMe),
        ("group", Group),
        ("groupexists", GroupExists),
        ("guid", Guid),
        ("hang", Hang),
        ("hanging", Hanging),
        ("hashitch", HasHitch),
        ("health", Health),
        ("heard", Heard),
        ("hit", Hit),
        ("hold", Hold),
        ("holsterweapon", HolsterWeapon),
        ("home", Home),
        ("idle", Idle),
        ("if", If),
        ("in", In),
        ("incomingattack", IncomingAttack),
        ("incomingattacktime", IncomingAttackTime),
        ("incomingattackwillblock", IncomingAttackWillBlock),
        ("index", Index),
        ("integer", Integer),
        ("intensity", Intensity),
        ("is", Is),
        ("isdone", IsDone),
        ("ishome", IsHome),
        ("isrestricted", IsRestricted),
        ("joingroup", JoinGroup),
        ("jump", Jump),
        ("knockeddown", KnockedDown),
        ("ks", Ks),
        ("label", Label),
        ("leader", Leader),
        ("leavegroup", LeaveGroup),
        ("left", Left),
        ("level", Level),
        ("levelcomplete", LevelComplete),
        ("lineofsight", LineOfSight),
        ("listen", Listen),
        ("location", Location),
        ("log", Log),
        ("look", Look),
        ("loop", Loop),
        ("magnitude", Magnitude),
        ("makeexplosion", MakeExplosion),
        ("makefx", MakeFX),
        ("makenoise", MakeNoise),
        ("makeprojectile", MakeProjectile),
        ("makestring", MakeString),
        ("max", Max),
        ("me", Me),
        ("miss", Miss),
        ("min", Min),
        ("musicplay", MusicPlay),
        ("musicstop", MusicStop),
        ("name", Name),
        ("navpoint", NavPoint),
        ("neutral", Neutral),
        ("next", Next),
        ("normalize", Normalize),
        ("not", Not),
        ("of", Of),
        ("offset", Offset),
        ("oncamera", OnCamera),
        ("onlyrunning", OnlyRunning),
        ("onlystanding", OnlyStanding),
        ("or", Or),
        ("orientation", Orientation),
        ("padrumblelargemotor", PadRumbleLargeMotor),
        ("padrumblelargermotorstop", PadRumbleLargeMotorStop),
        ("padrumblepause", PadRumblePause),
        ("padrumbleresume", PadRumbleResume),
        ("padrumblesmallmotor", PadRumbleSmallMotor),
        ("padrumblesmallmotorstop", PadRumbleSmallMotorStop),
        ("padrumbleStopmotors", PadRumbleStopMotors),
        ("parent", Parent),
        ("pass", Pass),
        ("path", Path),
        ("patrol", Patrol),
        ("pause", Pause),
        ("pickup", Pickup),
        ("pitch", Pitch),
        ("pitchramp", PitchRamp),
        ("play", Play),
        ("playambientsound", PlayAmbientSound),
        ("playactionanimation", PlayActionAnimation),
        ("playanimation", PlayAnimation),
        ("player", Player),
        ("playertaskbegin", PlayerTaskBegin),
        ("playertasksuccessful", PlayerTaskSuccessful),
        ("playertaskfailure", PlayerTaskFailure),
        ("position", Position),
        ("rampuptime", RampUpTime),
        ("random", Random),
        ("randomrange", RandomRange),
        ("randomrangefloat", RandomRangeFloat),
        ("range", Range),
        ("rate", Rate),
        ("receiveaction", ReceiveAction),
        ("receivemessage", ReceiveMessage),
        ("remove", Remove),
        ("resethealth", ResetHealth),
        ("restart", Restart),
        ("retreat", Retreat),
        ("right", Right),
        ("room", Room),
        ("rungame", RunGame),
        ("savepoint", SavePoint),
        ("scan", Scan),
        ("script", Script),
        ("seconds", Seconds),
        ("sectioncreated", SectionCreated),
        ("sendaction", SendAction),
        ("sendgroupmessage", SendGroupMessage),
        ("sendgroupmembersmessage", SendGroupMembersMessage),
        ("sendmessage", SendMessage),
        ("sequence", Sequence),
        ("set", Set),
        ("setactiveweapon", SetActiveWeapon),
        ("setactorenabled", SetActorEnabled),
        ("setattacktable", SetAttackTable),
        ("setcrouch", SetCrouch),
        ("setcurve", SetCurve),
        ("setcurveknot", SetCurveKnot),
        ("setcurveks", SetCurveKs),
        ("setcurvelerp", SetCurveLerp),
        ("setcurvelookalongdistance", SetCurveLookAlongDistance),
        ("setcurvelookalongdirection", SetCurveLookAlongDirection),
        ("setcurvelookatactor", SetCurveLookAtActor),
        ("setcurvephase", SetCurvePhase),
        ("setcurvepingpong", SetCurvePingPong),
        ("setcurvespeed", SetCurveSpeed),
        ("setendframe", SetEndFrame),
        ("setfaction", SetFaction),
        ("setfogclamp", SetFogClamp),
        ("setfogcolor", SetFogColor),
        ("setfogpalettepower", SetFogPalettePower),
        ("setfogrange", SetFogRange),
        ("setfogtype", SetFogType),
        ("setfullscreencolor", SetFullScreenColor),
        ("setfullscreenmotionblur", SetFullScreenMotionBlur),
        ("setframe", SetFrame),
        ("sethealth", SetHealth),
        ("sethud", SetHud),
        ("setlerpcurve", SetLerpCurve),
        ("setlookupcurve", SetLookUpCurve),
        ("setlightparameter", SetLightParameter),
        ("setrate", SetRate),
        ("setshaderglobal", SetShaderGlobal),
        ("setshaderlocal", SetShaderLocal),
        ("setstartframe", SetStartFrame),
        ("setunbreakable", SetUnbreakable),
        ("setupdatestate", SetUpdateState),
        ("setweaponchargestate", SetWeaponChargeState),
        ("setweaponfiremode", SetWeaponFireMode),
        ("shoot", Shoot),
        ("shootdistance", ShootDistance),
        ("sin", Sin),
        ("size", Size),
        ("sort", Sort),
        ("sound", Sound),
        ("spawn", Spawn),
        ("sqrt", Sqrt),
        ("speed", Speed),
        ("spotangle", SpotAngle),
        ("stack", Stack),
        ("stackdump", StackDump),
        ("start", Start),
        ("startcutsceneaudio", StartCutSceneAudio),
        ("startfighting", StartFighting),
        ("startshooting", StartShooting),
        ("status", Status),
        ("stop", Stop),
        ("string", StringKw),
        ("successiveattacks", SuccessiveAttacks),
        ("support", Support),
        ("switch", Switch),
        ("takecover", TakeCover),
        ("teleport", Teleport),
        ("then", Then),
        ("time", Time),
        ("timer", Timer),
        ("times", Times),
        ("to", To),
        ("totaltime", TotalTime),
        ("trackactor", TrackActor),
        ("trackclosest", TrackClosest),
        ("trackpos", TrackPos),
        ("triggerinside", TriggerInside),
        ("triggeroutside", TriggerOutside),
        ("triggerentered", TriggerEntered),
        ("triggerexited", TriggerExited),
        ("triggergetactorsinside", TriggerGetActorsInside),
        ("turret", Turret),
        ("unarmed", Unarmed),
        ("usepad", UsePad),
        ("uses", Uses),
        ("variable", Variable),
        ("vector", Vector),
        ("volume", Volume),
        ("volumeramp", VolumeRamp),
        ("weapondrawn", WeaponDrawn),
        ("whenever", Whenever),
        ("while", While),
        ("with", With),
        ("within", Within),
        ("x", X),
        ("y", Y),
        ("z", Z),
    ];
    pairs.iter().map(|(k, v)| (k.to_string(), *v)).collect()
}
